# Generated by Django 3.2.13 on 2022-05-05 17:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_student'),
        ('teachers', '0002_teacherprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_hour_per_week', models.IntegerField()),
                ('lang_barrier', models.BooleanField(default=False)),
                ('tuition_start_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tuition_end_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('am_or_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='PM', max_length=2)),
                ('age_range', models.ManyToManyField(to='teachers.StudentAgeRange')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('want_to_learn', models.ManyToManyField(to='students.Subjects')),
            ],
        ),
    ]
