# Generated by Django 3.2.13 on 2022-05-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_name'),
        ('teachers', '0002_teacherprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='users.teacher'),
        ),
    ]
