# Generated by Django 3.2.13 on 2022-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20220507_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('subject', models.CharField(choices=[('MATH', 'Math'), ('SCIENCE', 'Scient'), ('TIBETAN', 'Tibetan'), ('CODING', 'Coding')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='can_teach_to_student',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teaching_subjects',
        ),
        migrations.DeleteModel(
            name='TeachingSubject',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='curriculums',
            field=models.ManyToManyField(to='teachers.Curriculum'),
        ),
    ]
