# Generated by Django 3.2.13 on 2022-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_rename_work_experience_teacherprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.CharField(choices=[('MATH', 'Math'), ('SCIENCE', 'Science'), ('TIBETAN', 'Tibetan'), ('CODING', 'Coding')], max_length=20),
        ),
    ]
