# Generated by Django 3.2.13 on 2022-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_curriculum_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='comfortable_with_english',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='languages',
            field=models.ManyToManyField(to='teachers.Language'),
        ),
    ]
