# Generated by Django 3.2.13 on 2022-05-08 17:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teacherprofile_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=tinymce.models.HTMLField(),
        ),
    ]
