# Generated by Django 3.2.13 on 2022-05-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_auto_20220509_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='curriculums',
            field=models.ManyToManyField(blank=True, to='teachers.Curriculum'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='teachers.Language'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='students',
            field=models.ManyToManyField(blank=True, to='teachers.StudentAgeRange'),
        ),
    ]
