# Generated by Django 3.2.13 on 2022-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_alter_teacherprofile_fee_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='fee_per_hour',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fee per Hour in $ USD'),
        ),
    ]
